### SIB - Exercise 1
##### 1.1 In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [1]:
from si.io.csv_file import read_csv

iris_data = read_csv('C:/Users/35192/si/datasets/iris/iris.csv', features=True, label=True)

print("Shape of iris dataset:",iris_data.shape())
print("Features:", iris_data.features)
print("Label:", iris_data.label)
print(iris_data.X)

Shape of iris dataset: (150, 4)
Features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
Label: class
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.

##### 1.2) Select the penultimate independent variable. What is the dimension of the resulting array?

In [2]:
penultima_variavel = iris_data.X[:, -2]
print("Dimensão resultante da matriz:", penultima_variavel.shape)
print("Dimensão:",penultima_variavel.ndim)

Dimensão resultante da matriz: (150,)
Dimensão: 1


##### 1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [3]:
ultimas_amostras = iris_data.X[-10:,:]

medias_10= ultimas_amostras.mean(axis=0)
print(medias_10)

[6.45 3.03 5.33 2.17]


##### 1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?

In [4]:
import numpy as np

filtrar = np.all(iris_data.X <= 6, axis=1)
num_amostras = iris_data.X[filtrar]

print("Número de amostras:", num_amostras.shape[0])

Número de amostras: 89


##### 1.5) Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [5]:
amostra = iris_data.y != "Iris-setosa"
amostras_filtradas = iris_data.X[amostra]

print("Número de amostras:", amostras_filtradas.shape[0])

Número de amostras: 100
